# Generated by Django 5.2.11 on 2026-03-02 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanDetails',
            new_name='LoanDetail',
        ),
    ]
